name: Deploy ToDo App

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-central-1
  ECR_REPO: todo-app-dp011
  TF_LOG: DEBUG
  TF_VAR_node_role_arn: arn:aws:iam::325583868777:role/AWSEKSNode_RPC
  TF_VAR_ssh_key_name: rpc-ipocFrank

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Login no ECR
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build e Push da imagem Docker
        run: |
          IMAGE_TAG=$(date +%s)
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          IMAGE_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

          echo "node_role_arn = \"$TF_VAR_node_role_arn\"" > terraform/terraform.tfvars
          echo "ssh_key_name  = \"$TF_VAR_ssh_key_name\""  >> terraform/terraform.tfvars
          echo "todo_image    = \"$IMAGE_URI\""            >> terraform/terraform.tfvars

      - name: Criar repositório ECR com Terraform
        working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Deploy com Terraform
        working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve
