name: Deploy ToDo App

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-central-1
  ECR_REPO: todo-app-dp011
  TF_LOG: DEBUG
  TF_VAR_node_role_arn: arn:aws:iam::325583868777:role/role-for-eksDeepDiveFrankfurt-eks-cluster
  TF_VAR_ssh_key_name: rpc

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
      
      - name: Configurar AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Criar repositório ECR com Terraform
        working-directory: terraform
        run: |
          terraform init
          terraform apply \
            -target=aws_ecr_repository.todo_app \
            -auto-approve

      - name: Login no ECR
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

            - name: Build e Push da imagem Docker
        run: |
          IMAGE_TAG=$(date +%s)
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          IMAGE_URI=$ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/$ECR_REPO:$IMAGE_TAG
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

          # Atualiza o k8s-resources.tf com a nova imagem
          sed -i "s|image = .*|image = \"$IMAGE_URI\"|" terraform/k8s-resources.tf


      - name: Substituir imagem no Terraform (sed)
        run: |
          sed -i "s|image = .*|image = \"$IMAGE_URI\"|" terraform/k8s-resources.tf

      - name: Deploy com Terraform
        working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve
